# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Dictionary_config = debug

else ifeq ($(config),release)
  Dictionary_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Dictionary

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Dictionary:
ifneq (,$(Dictionary_config))
	@echo "==== Building Dictionary ($(Dictionary_config)) ===="
	@${MAKE} --no-print-directory -C . -f Dictionary.make config=$(Dictionary_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Dictionary.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Dictionary"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"